### ISSUE TITLE
template_redirect hook never fires for preview?

### ISSUE THREAD

**Issue by justinwhall** [Automattic/vip-go-nextjs-skeleton#29] opened 2021-11-07 22:33 UTC
Say we have the following:

`site_url`: `https://backend.dev` (WordPress)
`home_url`: `https//frontend.dev` (Next app)

`preview.php` makes sense theoretically (and if I manually generate a token) but the WordPress admin for, say, `hello world` is going to have a preview  button that links to something like:

```
https://frontend.dev/helloworld?preview=true...
```

During the above request, WordPress, of course, never spins up thus the `template_redirect` action hook [here](https://github.com/Automattic/vip-decoupled-bundle/blob/trunk/preview/preview.php#L16), is never fired  and the whole preview process never kicks off.

Am I missing something? 🙃

**Comment by justinwhall** [comment] 2021-11-09 16:05
Alright, I see what's up. The custom server [redirects previews back to WP if it's a preview](https://github.com/Automattic/vip-go-nextjs-skeleton/blob/trunk/server/index.js#L69). 

~~For some reason this is not working. Perhaps it is related to the new NEXT 12 `_middleware` API.~~

Actually it is. However, if the `home_url` is different than the `site_url`,  redirecting and landing on say: `https://backend.dev/hello-world` will not trigger `template-redirect`.

**Comment by kvnang** [comment] 2021-11-09 17:28
I also experienced the same issue. I think the issue is fundamentally, as you said first, in WP. I found that by defining `WP_URL` on `wp-config.php` to some external URL leads to `template_redirect` not firing at all in this case. I haven't looked into this further as to why this is the case. But what works for our purpose is to not change `WP_URL`, and somehow customize the WP Plugin to fit our needs (which is very much a hot fix at the moment).

**Comment by kvnang** [comment] 2021-11-09 17:55
I've experienced the same issue @justinwhall, but your suggestion on using `_middleware` actually works for me. I still have `WP_HOME` defined pointing to the Next.js URL, and a middleware parses the URL and handles the redirection back to WP for the rest of the operations.

I haven't tested why the VIP's custom Next server doesn't work, but I've been avoiding that in any event as it seems an unnecessary overhead for our purpose.

My middleware looks like this:

```
// pages/_middleware.ts

import { NextRequest, NextResponse } from 'next/server';

export function middleware(req: NextRequest) {
  const url = req.nextUrl;

  const p = url.searchParams.get('p');
  const preview = url.searchParams.get('preview');
  const previewId = url.searchParams.get('preview_id');

  if ((preview === 'true' && previewId) || p) {
    const query = req.url.substr(req.url.indexOf('?'));
    return NextResponse.redirect(
      `${process.env.NEXT_PUBLIC_WORDPRESS_URL}/${query}`,
      302
    );
  }
}

```

Wonder if this would work for you?

**Comment by justinwhall** [comment] 2021-11-09 19:01
@kvnang, just to be clear,  I have something similar and the redirect does work. The issue is that if `home_url` is set to the that of the Next App, then the `template_redirect` never fires.

**Comment by kvnang** [comment] 2021-11-09 21:21
@justinwhall I cannot replicate that issue so far, and `template_redirect` called by VIP plugin is executed properly on redirection from Next app.

Does the redirection works if you just paste the preview URL, e.g. `https://wpbackend.dev/?p=123&preview=true`?

This is how I define the frontend URL pointing to Next app:
`define('WP_HOME', 'https://nextfrontend.dev');`

**Comment by chriszarate** [comment] 2021-11-11 23:58
> However, if the home_url is different than the site_url, redirecting and landing on say: https://backend.dev/hello-world will not trigger template-redirect.

@justinwhall Are you experiencing this on a development site or a deployed site? When you say that it does not trigger `template_redirect`, what happens instead? If you can provide some more detail I'd love to dig into this more.

Are you, by chance, setting `wp_home` and `siteurl` to URLs with different HTTP ports? When this is the case, WordPress balks and redirects to the port used by `wp_home`.

**Comment by chriszarate** [comment] 2022-08-01 16:09
Closing, but please reopen if you can replicate.

**Closed as completed by chriszarate** 2022-08-01 16:09 UTC
